name: Check

on: 
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Ready'
        required: true
        default: 'Ok'

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Prepare the environment
      run: |
        cd ./test
        sudo mkdir tempo
        ./build
